{% set version = "3.1.0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: f5dc2fe0c6c645950223c156cec378977c5700d361812dcc526c09d01315f455

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
    - pyke
  run:
    - python
    - cartopy >=0.18
    - cf-units
    - cftime >=1.5.0
    - dask >=2
    - matplotlib-base
    - netcdf4 >=1.4
    - numpy >=1.14,!=1.15.2
    - pyke
    - scipy
    - python-xxhash

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
