{% set version = "3.1.0rc0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: d4cf6b827aa15fa6f93078143cd865111e12600b7c68ebfe84e4022c7f3dbfe8

build:
  number: 0
  skip: true  # [py<37]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - cartopy >=0.18
    - cf-units
    - cftime >=1.5.0
    - dask >=2
    - matplotlib-base
    - netcdf4 >=1.4
    - numpy >=1.14,!=1.15.2
    - scipy
    - python-xxhash

test:
  imports:
    - iris

about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
