{% set version = "2.4.0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 7708d05bd83da5dd8fc5df8bae02767b8b5a1e814732c8eaaf11c8298508f0fc

build:
  number: 0

requirements:
  host:
    - python
    - pip
    - pyke
    - six
  run:
    - python
    - cartopy >=0.14
    - cf-units >=2
    - cftime !=1.0.2.1
    - dask
    - matplotlib-base
    - netcdf4 >=1.4
    - numpy >=1.14,!=1.15.2
    - pyke
    - scipy
    - six

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: http://www.scitools.org.uk/iris
  license: GNU Lesser General Public License
  license_family: GPL
  license_file: COPYING.LESSER
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
