{% set version = "2.0.0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 8605ab92c67d622e83fff6d7169fe154d9f8610edd8463b697b574884c158ba2

build:
  number: 3

requirements:
  build:
    - python
    - pip
    - cartopy >=0.14
    - cf_units
    - dask >=0.17.1
    - numpy
    - pyke
    - scipy
    - six
  run:
    - python
    - cartopy >=0.14
    - cf_units
    - dask >=0.17.1
    - matplotlib
    - numpy
    - pyke
    - scipy
    - six

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: http://www.scitools.org.uk/iris
  license: GPL3
  license_family: GPL3
  license_file: README.md
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
