{% set version = "3.0.3" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: a514631f42b3301e3764149cc03001391eac3e81a749aa5641d598682a3489f0

build:
  number: 0
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - pyke
  run:
    - python
    - cartopy >=0.18
    - cf-units >=2.1.5
    - cftime <1.3.0
    - dask >=2
    - matplotlib-base
    - netcdf4 >=1.4
    - numpy >=1.14,!=1.15.2
    - pyke
    - scipy
    - python-xxhash

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
