{% set version = "3.8.1" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scitools-iris/scitools-iris-{{ version }}.tar.gz
  sha256: bf1f35053c16c14938ee0a1a6cfa7ab60804cf1ec79bac5b550179354370d4fc

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

outputs:
  - name: iris
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python >=3.9
        - pip
        - setuptools >=64
        - setuptools-scm >=7
      run:
        - python >=3.9
        - cartopy >=0.21
        - cf-units >=3.1
        - cftime >=1.5
        - dask-core >=2022.9.0
        - libnetcdf !=4.9.1
        - matplotlib-base >=3.5
        - netcdf4
        - numpy >=1.23,!=1.24.3
        - pyproj
        - scipy
        - shapely !=1.8.3
        - python-xxhash

    test:
      imports:
        - iris

  - name: scitools-iris
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('iris', max_pin="x.x.x") }}
    test:
      imports:
        - iris
about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - ocefpaf
    - bjlittle
    - lbdreyer
    - pp-mo
    - stephenworsley
    - trexfeathers
    - ESadek-MO
