{% set version = "1.11.0" %}

package:
    name: iris
    version: {{ version }}

source:
    fn: iris-v{{ version }}.tar.gz
    url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
    sha256: 95cd7381a994ec79a99b59ababe7c179c0416034cb450be62b83b1908a807316
    patches:
        # Issue reported in https://github.com/SciTools/iris/issues/2004.
        # We work around this in build.sh.
        - no_compile_setup.patch  # [osx]

build:
    number: 0

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - biggus >=0.14
        - cartopy >=0.14
        - netcdf4
        - cf_units
        - pyke
        - mo_pack  # [not win]
        - nc_time_axis
        - iris-grib  # [not win and not py3k]
    run:
        - python
        - numpy
        - scipy
        - biggus >=0.14
        - cartopy >=0.14
        - netcdf4
        - cf_units
        - pyke
        - mo_pack  # [not win]
        - matplotlib
        - nc_time_axis
        - iris-grib  # [not win and not py3k]

test:
    imports:
        - iris
        - iris.fileformats._pyke_rules.compiled_krb

about:
    home: http://www.scitools.org.uk/iris
    license: GPL3
    license_family: GPL3
    license_file: README.md
    summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
        - bjlittle
