{% set version = "2.2.1" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 6a540e6201d6e4cd5ecb10393989c6d1b16559f95a56cdab3fcf31d9e2154c8a

build:
  number: 0

requirements:
  build:
    - python
    - pip
    - cartopy >=0.14
    - cf-units >=2
    - cftime !=1.0.2.1
    - dask
    - numpy >=1.14
    - pyke
    - scipy
    - six
  run:
    - python
    - cartopy >=0.14
    - cf-units >=2
    - cftime !=1.0.2.1
    - dask
    - matplotlib >=2
    - netcdf4 >=1.4
    - numpy >=1.14, !=1.15.2
    - pyke
    - scipy
    - six

test:
  imports:
    - iris
    - iris.fileformats._pyke_rules.compiled_krb

about:
  home: http://www.scitools.org.uk/iris
  license: GPL3
  license_family: GPL3
  license_file: README.md
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - corinnebosley
