{% set version = "1.9.2" %}

package:
    name: iris
    version: {{ version }}

source:
    fn: iris-v{{ version }}.tar.gz
    url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
    sha256: 93f2cfe1c14aad293103727004863d09f21ea61de337aa73cb96a706df0b6133
    patches:
        # Issue reported in https://github.com/SciTools/iris/issues/2004.
        # We work around this in build.sh.
        - no_compile_setup.patch  # [osx]

build:
    number: 1
    skip: True  # [osx]

requirements:
    build:
        - python
        - setuptools
        - numpy
        - scipy
        - biggus
        - cartopy
        - netcdf4
        - cf_units
        - pyke
        - mo_pack  # [not win]
    run:
        - python
        - numpy
        - scipy
        - biggus
        - cartopy
        - netcdf4
        - cf_units
        - pyke
        - mo_pack  # [not win]
        - matplotlib
        - python-ecmwf_grib >=1.12.1  # [not win and not py3k]

test:
    imports:
        - iris
        - iris.fileformats.pp_packing  # [not win]
        - iris.fileformats._pyke_rules.compiled_krb

about:
    home: http://www.scitools.org.uk/iris
    license: GNU Lesser General Public License
    summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
    recipe-maintainers:
        - pelson
        - rhattersley
        - ocefpaf
