{% set version = "3.3.0rc0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/scitools-iris/scitools-iris-{{ version }}.tar.gz
  sha256: c638a75ed0f29b610c4bfeff25fe59315e7cc108382afd1b26df2575e7f7ed02

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

outputs:
  - name: iris  
    requirements:
      host:
        - python >=3.8
        - pip
        - setuptools >=64
        - setuptools-scm >=7
      run:
        - python >=3.8
        - cartopy >=0.20
        - cf-units
        - cftime
        - dask-core >=2
        - matplotlib-base
        - netcdf4
        - numpy >=1.19
        - pyproj
        - scipy
        - shapely <1.8.3
        - python-xxhash

    test:
      imports:
        - iris

  - name: scitools-iris
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('iris', max_pin="x.x.x") }}
    test:
      imports:
        - iris
about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
    - jamesp
    - stephenworsley
    - trexfeathers
    - wjbenfold
