{% set version = "3.0.0rc0" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://github.com/SciTools/iris/archive/v{{ version }}.tar.gz
  sha256: 5a9a08870af18a1f128eef3b15afadcf68579346668ae929805e057b5f60d64c

build:
  number: 1
  skip: true  # [py<36]

requirements:
  host:
    - python
    - pip
    - pyke
  run:
    - python
    - cartopy >=0.18
    - cf-units >=2
    - cftime !=1.0.2.1
    - dask >=2
    - matplotlib-base
    - netcdf4 >=1.4
    - numpy >=1.14,!=1.15.2
    - pyke
    - scipy
    - python-xxhash

about:
  home: http://www.scitools.org.uk/iris
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.LESSER
  summary: 'Analyse and visualise meteorological and oceanographic data sets.'

extra:
  recipe-maintainers:
    - pelson
    - rhattersley
    - ocefpaf
    - bjlittle
    - DPeterK
    - corinnebosley
    - lbdreyer
    - pp-mo
