{% set python_min = '3.10' %}
{% set version = "3.11.1" %}

package:
  name: iris
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/scitools-iris/scitools_iris-{{ version }}.tar.gz
  sha256: 38bbde68dd85708cf0e5bfec2118dec3d3b63f818ce9135a1318e5aa4eac1ca7

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 1

outputs:
  - name: iris
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=64
        - setuptools-scm >=7
      run:
        - python >={{ python_min }}
        - cartopy >=0.21
        - cf-units >=3.1
        - cftime >=1.5
        - dask-core >=2022.9.0, !=2024.8.0, <2024.9
        - libnetcdf !=4.9.1
        - matplotlib-base >=3.5, !=3.9.1
        - netcdf4
        - numpy >=1.24,!=1.24.3
        - python-xxhash
        - pyproj
        - scipy
        - shapely !=1.8.3

    test:
      requires:
        - python {{ python_min }}
      imports:
        - iris

  - name: scitools-iris
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('iris', max_pin="x.x.x") }}
    test:
      imports:
        - iris
about:
  home: https://scitools-iris.readthedocs.io/en/stable/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Analyse and visualise meteorological and oceanographic data sets.

extra:
  recipe-maintainers:
    - ocefpaf
    - bjlittle
    - lbdreyer
    - pp-mo
    - stephenworsley
    - trexfeathers
    - ESadek-MO
    - HGWright
    - ukmo-ccbunney
